In [2]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series([1,2,3,4,5,6,7,np.nan,9,10]) #create series
s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     NaN
8     9.0
9    10.0
dtype: float64

In [ ]:
d =pd.date_range('20220101',periods = 12)

In [ ]:
d

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
print(np.random.randn(5))
print(np.random.rand(5))

[ 0.34851365  0.56078264 -0.02177198 -0.90498175 -1.68986874]
[0.8652244  0.03576005 0.66126201 0.07572644 0.63803488]

In [ ]:
df = pd.DataFrame(np.random.randn(12,4),index=d,columns=['A','B','C','D'])

In [ ]:
df

           A         B         C         D
0   1.024214 -0.494531  0.952389  1.693073
1   2.055796  0.632646 -0.750946  0.938583
2   0.704089  1.811741  0.874817 -0.331912
3  -1.069327 -0.494262  1.130078 -1.075123
4  -0.863790  0.273709  0.692418 -1.086558
5   0.482999  0.681838  1.863359  0.862125
6  -0.166089  1.950849  0.795552  1.000980
7   0.720998 -2.123512 -1.143435 -0.041209
8   0.343043 -0.571489 -0.992427 -0.134852
9  -1.332469 -0.016991  0.574122  0.107167
10  0.660605 -0.643193  0.116627  2.171658
11  1.197962  0.756616  1.648501  0.715131

In [3]:
d = np.random.randint(0,100,5)
d

array([69, 61, 72, 94, 72])

In [ ]:
df = pd.DataFrame(np.random.randn(12,4),columns=['A','B','C','D'])
df

In [ ]:
df = pd.DataFrame(np.random.randn(12,4),columns=['A','B','C','D'])
df

           A         B         C         D
0  -0.222818 -0.987854 -0.132261  1.001140
1  -0.094198 -0.355946 -1.338142 -0.890898
2   1.285666  1.377628 -1.598111  0.659097
3   0.256467  0.352842 -1.317094 -0.961853
4   0.223193  1.235536  0.771898  0.310461
5   0.101563 -0.123889 -1.155347 -2.121286
6  -0.373925  0.880131 -0.699285  0.831670
7  -0.476178  1.341415 -0.457671  0.766185
8   1.294335 -0.948910 -0.316942 -1.000208
9  -0.441210  0.077299  0.913070  1.108620
10  1.770592 -0.470422  0.956465 -0.314712
11 -0.100541 -0.709585 -0.302274  0.429732

In [ ]:
df = pd.DataFrame(np.random.randn(12,4))
df

           0         1         2         3
0  -0.490645 -0.238915 -0.598464 -0.716900
1   0.461712 -1.372035  2.473570 -0.971888
2  -2.605147 -1.291542 -0.881211  0.544629
3  -0.281635 -1.648718  0.330746 -0.170263
4   2.018012  0.044389 -3.208404  1.310811
5  -0.183209  0.959207 -0.371957  0.437465
6  -0.425630 -0.824457 -0.159746 -0.594085
7   0.083047 -0.331664  1.646148  1.293330
8   0.668254 -0.985623  0.273068 -0.686731
9  -0.583975  0.193068  0.812680 -1.546529
10  2.883803  0.792107  0.244139  1.130160
11 -0.540850  0.215657 -0.508202  0.680647

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [ ]:
print(df.loc[[ 1,2]])

   calories  duration
1       380        40
2       390        45

In [ ]:
#When using [], the result is a Pandas DataFrame.

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

In [ ]:
#Load a comma separated file (CSV file) into a DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df)

In [ ]:
import pandas as pd

df = pd.read_json('data.json')

print(df.to_string())

In [ ]:
#Load a Python Dictionary into a DataFrame:

import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [ ]:
# Get a quick overview by printing the first 10 rows of the DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))
print(df.head())

In [ ]:
# There is also a tail() method for viewing the last rows of the DataFrame.

# The tail() method returns the headers and a specified number of rows, starting from the bottom.

# Example
# Print the last 5 rows of the DataFrame:

print(df.tail())

In [ ]:
# Print information about the data:

print(df.info())

The info() method also tells us how many Non-Null values there are present in each column
Empty values, or Null values, can be bad when analyzing data, and you should consider removing rows with empty values. This is a step towards what is called cleaning data, and you will learn more about that in the next chapters.

In [ ]:
df.describe()
df.dtypes
df.index
df.columns
df.sort_index(axis=1, ascending=False)
df.sort_values(by='columnname')
df['column1'] gives the single column
df[0:3] using the rows

df.column1.value_counts()
df.column1.sort_values()
df.sort_values(by=['column1','column2'])

Data cleaning means fixing bad data in your data set.

Bad data could be:

Empty cells
Data in wrong format
Wrong data
Duplicates

In [ ]:
Return a new Data Frame with no empty cells:

import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

By default, the dropna() method returns a new DataFrame, and will not change the original.

If you want to change the original DataFrame, use the inplace = True argument:

Example
Remove all rows with NULL values:

In [ ]:

import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df)

 the dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

In [ ]:
#Replace NULL values with the number 130:

import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(130, inplace = True)

In [ ]:
Calculate the MEAN, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x, inplace = True)

In [ ]:
Calculate the MEDIAN, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True)

In [ ]:
Calculate the MODE, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

In [ ]:
Loop through all values in the "Duration" column.

If the value is higher than 120, set it to 120:

for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 120

In [ ]:
Delete rows where "Duration" is higher than 120:

for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)

In [ ]:
To remove duplicates, use the drop_duplicates() method.

Example
Remove all duplicates:

df.drop_duplicates(inplace = True)

In [ ]:
Show the relationship between the columns:

df.corr()

In [ ]:
Import pyplot from Matplotlib and visualize our DataFrame:

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.plot()

plt.show()

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.plot(kind = 'scatter', x = 'Duration', y = 'Calories')

plt.show()

FileNotFoundError: ignored

In [ ]:
# Let's create another scatterplot, where there is a bad relationship between the columns, like "Duration" and "Maxpulse", with the correlation 0.009403:

# Example
# A scatterplot where there are no relationship between the columns:

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.plot(kind = 'scatter', x = 'Duration', y = 'Maxpulse')

plt.show()

In [ ]:
# Use the kind argument to specify that you want a histogram:

# kind = 'hist'

# A histogram needs only one column.

# A histogram shows us the frequency of each interval, e.g. how many workouts lasted between 50 and 60 minutes?

df["Duration"].plot(kind = 'hist')