In [1]:
# prompt: create a dataframe with 2 columns and 10 rows

import pandas as pd

data = {'column1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
       'column2': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']}

df = pd.DataFrame(data)

print(df)

   column1  column2
0        0       10
1        1       11
2        2       12
3        3       13
4        4       14
5        5       15
6        6       16
7        7       17
8        8       18
9        9       19